export const OK: "OK";
export const DAY_SECONDS: number;
export const USERNAME_DEFAULT: "default";
export const ERR_CLIENT_NAMES: "ERR Client names cannot contain spaces, newlines or special characters.";
export const ERR_CURSOR: "ERR invalid cursor";
export const ERR_DB_INDEX: "ERR DB index is out of range";
export const ERR_EXECABORT: "EXECABORT Transaction discarded because of previous errors.";
export const ERR_HASH_FLOAT: "ERR hash value is not a float";
export const ERR_HASH_INTEGER: "ERR hash value is not an integer";
export const ERR_NOAUTH: "NOAUTH Authentication required.";
export const ERR_NOT_INTEGER: "ERR value is not an integer or out of range";
export const ERR_SYNTAX: "ERR syntax error";
export const ERR_TYPE: "WRONGTYPE Operation against a key holding the wrong kind of value";
export const ERR_VALUE_FLOAT: "ERR value is not a valid float";
export const ERR_WRONGPASS: "WRONGPASS invalid username-password pair or user is disabled.";
export const NX: "NX";
export const XX: "XX";
export const GT: "GT";
export const LT: "LT";
export const KEY_NOT_EXISTS: -2;
export const KEY_NO_EXPIRY: -1;
export const TRUE: 1;
export const FALSE: 0;
export const TYPE_NONE: "none";
export const TYPE_STRING: "string";
export const TYPE_HASH: "hash";
